name: "cabal_9-0"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal_9-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: |
          nix-shell nix/cabal_9-0.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always"

      - name: Doc Tests
        run: |
          nix-shell nix/cabal_8-10.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             RUN_DOCTEST=1 cabal test doctest"

      - name: Unit Tests
        run: |
          nix-shell nix/cabal_8-10.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             cabal test unit"